In [41]:
from sklearn.datasets import load_iris
from sklearn.linear_model import LogisticRegression
import pandas as pd
import numpy as np

In [96]:
X_train =  pd.read_csv('~/Desktop/562/Project2/X_train_scaled.csv')
X_test = pd.read_csv('~/Desktop/562/Project2/X_test_scaled.csv')
X_oot = pd.read_csv('~/Desktop/562/Project2/X_oot_scaled.csv')
y_train = pd.read_csv('~/Desktop/562/Project2/y_train.csv')
y_test = pd.read_csv('~/Desktop/562/Project2/y_test.csv')
y_oot = pd.read_csv('~/Desktop/562/Project2/y_oot.csv')

In [97]:
logreg = LogisticRegression()
logreg.fit(X_train, y_train)

/Users/kaichenchan/anaconda3/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/Users/kaichenchan/anaconda3/lib/python3.6/site-packages/sklearn/utils/validation.py:761: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)

In [98]:
#y_pred = logreg.predict(X_test)
probability = logreg.predict_proba(X_oot)[:,1]
probability

array([4.03845364e-06, 1.72905460e-02, 3.92429389e-03, ...,
       4.47321407e-03, 4.46347549e-03, 8.06952986e-03])

In [47]:
probability

0.003760073925561474

In [99]:
newDF = X_oot
newDF['prob'] = probability
newDF['org'] = y_oot
newDF.sort_values(by=['prob'],ascending = False,inplace=True)


In [100]:
newDF

amt_max_cardstate_15d  amt_max_cardstate_31d  freq_card_2d  \
9763                0.948685               0.762070     15.722801   
6122               20.883544              18.344696      0.020893   
6121               20.883544              18.344696     -0.166034   
6200                1.039501               0.842170      0.207821   
5286               22.927034              20.147063     -0.166034   
5294               19.738224              17.635294     -0.166034   
7109               21.710542              19.074112      0.207821   
7110               21.710542              19.074112      0.207821   
5295               19.738224              17.334520      0.020893   
6065               20.322079              17.849482      0.207821   
6069               20.322079              17.849482     -0.166034   
9401                6.633042               5.775696      4.694080   
6064               20.322079              17.849482      0.020893   
6066               20.322079              17.849482     -0.352962   
6067               20.322079              17.849482     -0.166034   
6068               20.322079              17.849482      0.020893   
9757                1.256302               1.033389      0.020893   
6139               14.075353              12.339844      0.394748   
6138               14.075353              12.339844      0.207821   
9404                6.633042               5.775696      5.254862   
6144                9.316680               8.142676      1.703241   
6140               14.075353              12.339844      0.207821   
9403                6.633042               5.775696      5.067935   
9405                6.633042               5.775696      5.441790   
9402                6.633042               5.775696      4.881008   
6125               12.175612              10.664265      0.020893   
9395                2.605695               2.223559      3.572515   
9398                2.605695               2.223559      4.133298   
4142                1.260694               1.141471     -0.166034   
6111                7.075127               6.165616      1.516313   
...                      ...                    ...           ...   
4537               -0.501754              -0.517224     -0.352962   
2692               -0.494891              -0.511170     -0.352962   
9406               -0.509479              -0.524037     -0.352962   
3122               -0.494693              -0.510995     -0.352962   
4201               -0.475713              -0.494255     -0.352962   
2181               -0.505836              -0.520824      2.264023   
4120               -0.502357              -0.517755     -0.352962   
2705               -0.501668              -0.511170     -0.166034   
6309               -0.506241              -0.521181     -0.166034   
2704               -0.501668              -0.511170     -0.352962   
1082               -0.500342              -0.515978     -0.352962   
2691               -0.494891              -0.511170      0.020893   
9880               -0.476695              -0.495121     -0.352962   
4455               -0.489767              -0.506651     -0.352962   
2688               -0.494891              -0.511170     -0.352962   
9956               -0.510030              -0.524523     -0.352962   
7877               -0.485703              -0.503066     -0.352962   
2695               -0.494891              -0.511170      0.207821   
2829               -0.502323              -0.517725      4.320225   
2694               -0.494891              -0.511170      0.020893   
2693               -0.494891              -0.511170     -0.166034   
12321              -0.504002              -0.519206     -0.352962   
2687               -0.494891              -0.511170      0.207821   
3121               -0.508420              -0.523102     -0.166034   
929                -0.508377              -0.523064     -0.352962   
1498               -0.508420              -0.523102     -0.352962   
2686 

In [9]:
y_pred

array([0, 0, 0, ..., 0, 0, 0])

In [10]:
from sklearn.metrics import confusion_matrix
confusion_matrix = confusion_matrix(y_test, y_pred)
print(confusion_matrix)

[[24899    39]
 [  221    32]]


In [64]:
#FDR 3%
tdata = newDF
goods = tdata[tdata['org']==0]
bads = tdata[tdata['org'] == 1]
numgoods = len(goods)
numbads = len(bads)


topRows = int(round(len(tdata)*0.03))

temp1 = tdata.head(topRows)

needed1 = temp1.loc[:,'org']

FDR1 = sum(needed1)/numbads

FDR1
#FDR test

0.4901185770750988

In [90]:
tdata = newDF
goods = tdata[tdata['org']==0]
bads = tdata[tdata['org'] == 1]
numgoods = len(goods)
numbads = len(bads)


topRows = int(round(len(tdata)*0.03))

temp1 = tdata.head(topRows)

needed1 = temp1.loc[:,'org']

FDR1 = sum(needed1)/numbads

FDR1
#FDR test

0.5342902711323764

In [101]:
tdata = newDF
goods = tdata[tdata['org']==0]
bads = tdata[tdata['org'] == 1]
numgoods = len(goods)
numbads = len(bads)


topRows = int(round(len(tdata)*0.03))

temp1 = tdata.head(topRows)

needed1 = temp1.loc[:,'org']

FDR1 = sum(needed1)/numbads

FDR1
#FDR oot

0.24022346368715083

In [38]:
pwd()

'/Users/kaichenchan/Desktop/562'