In [86]:
import pandas as pd
import numpy as np
import scipy.stats as sps
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn import preprocessing

In [87]:
import keras
from keras.models import Sequential
from keras.layers import Dense
import numpy
# fix random seed for reproducibility
seed = 7
numpy.random.seed(seed)


In [88]:
X_train = pd.read_csv('X_train_scaled.csv')
X_test = pd.read_csv('X_test_scaled.csv')
y_train = pd.read_csv('y_train.csv')
y_test = pd.read_csv('y_test.csv')
X_oot = pd.read_csv('X_oot_scaled.csv')
y_oot = pd.read_csv('y_oot.csv')

In [89]:
# create model
model = Sequential()
model.add(Dense(5, input_dim=20, init='uniform', activation='relu'))
model.add(Dense(4, init='uniform', activation='relu'))
model.add(Dense(1, init='uniform', activation='sigmoid'))

/Users/Begins/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:3: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(5, input_dim=20, activation="relu", kernel_initializer="uniform")`
  This is separate from the ipykernel package so we can avoid doing imports until
/Users/Begins/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:4: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(4, activation="relu", kernel_initializer="uniform")`
  after removing the cwd from sys.path.
/Users/Begins/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:5: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(1, activation="sigmoid", kernel_initializer="uniform")`
  """


In [90]:
# Compile model
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [91]:
# Fit the model
model.fit(X_train, y_train, nb_epoch=20, batch_size=10)

/Users/Begins/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:2: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.
  


Epoch 1/20
58779/58779 [==============================] - 13s 224us/step - loss: 0.0582 - acc: 0.9893
Epoch 2/20
58779/58779 [==============================] - 13s 219us/step - loss: 0.0362 - acc: 0.9893
Epoch 3/20
58779/58779 [==============================] - 12s 206us/step - loss: 0.0340 - acc: 0.99091s 
Epoch 4/20
58779/58779 [==============================] - 12s 197us/step - loss: 0.0332 - acc: 0.9916
Epoch 5/20
58779/58779 [==============================] - 12s 196us/step - loss: 0.0326 - acc: 0.9920
Epoch 6/20
58779/58779 [==============================] - 12s 199us/step - loss: 0.0323 - acc: 0.9923
Epoch 7/20
58779/58779 [==============================] - 11s 194us/step - loss: 0.0319 - acc: 0.9924
Epoch 8/20
58779/58779 [==============================] - 12s 199us/step - loss: 0.0318 - acc: 0.9923
Epoch 9/20
58779/58779 [==============================] - 12s 198us/step - loss: 0.0319 - acc: 0.9924
Epoch 10/20
58779/58779 [==============================] - 12s 202us/step - los

In [92]:
# calculate predictions
y_train_pred = model.predict(X_train)
y_test_pred = model.predict(X_test)
y_oot_pred = model.predict(X_oot)

In [8]:
###y_pred

array([[1.32773295e-02],
       [6.89821551e-04],
       [1.27708263e-04],
       ...,
       [1.68911192e-05],
       [1.17018623e-02],
       [8.52348312e-05]], dtype=float32)

In [93]:
a_train=[]
prob_train = model.predict_proba(X_train)
for probabilty in prob_train:
    a_train.append(probabilty[0])

In [94]:
a_test=[]
prob_test = model.predict_proba(X_test)
for probabilty in prob_test:
    a_test.append(probabilty[0])

In [95]:
a_oot=[]
prob_oot = model.predict_proba(X_oot)
for probabilty in prob_oot:
    a_oot.append(probabilty[0])

In [96]:
newDF_train = X_train
newDF_train['prob'] = a_train
newDF_train['org'] = y_train
newDF_train.sort_values(by=['prob'],ascending = False, inplace = True)

newDF_test = X_test
newDF_test['prob'] = a_test
newDF_test['org'] = y_test
newDF_test.sort_values(by=['prob'],ascending = False, inplace = True)

newDF_oot = X_oot
newDF_oot['prob'] = a_oot
newDF_oot['org'] = y_oot
newDF_oot.sort_values(by=['prob'],ascending = False, inplace = True)


In [97]:
y_train_pred = [round(x[0]) for x in y_train_pred]
y_test_pred = [round(x[0]) for x in y_test_pred]
y_oot_pred = [round(x[0]) for x in y_oot_pred]

In [15]:
y_pred

[0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 1.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0

In [98]:
from sklearn.metrics import confusion_matrix
confusion_matrix = confusion_matrix(y_train, y_train_pred)
print(confusion_matrix)

[[58123    29]
 [  399   228]]


In [99]:
from sklearn.metrics import confusion_matrix
confusion_matrix = confusion_matrix(y_test, y_test_pred)
print(confusion_matrix)

[[24911    27]
 [  182    71]]


In [100]:
from sklearn.metrics import confusion_matrix
confusion_matrix = confusion_matrix(y_oot, y_oot_pred)
print(confusion_matrix)

[[12194    54]
 [  132    47]]


In [101]:
#FDR 3%
traindata = newDF_train
goods1 = traindata[traindata['org']==0]
bads1 = traindata[traindata['org'] == 1]
numgoods1 = len(goods1)
numbads1 = len(bads1)


topRows1 = int(round(len(traindata)*0.03))

temp1 = traindata.head(topRows1)

needed1 = temp1.loc[:,'org']

FDR1 = sum(needed1)/numbads1


In [102]:
#FDR 3%
testdata = newDF_test
goods2 = testdata[testdata['org']==0]
bads2 = testdata[testdata['org'] == 1]
numgoods2 = len(goods2)
numbads2 = len(bads2)


topRows2 = int(round(len(testdata)*0.03))

temp2 = testdata.head(topRows2)

needed2 = temp2.loc[:,'org']

FDR2 = sum(needed2)/numbads2


In [103]:
#FDR 3%
ootdata = newDF_oot
goods3 = ootdata[ootdata['org']==0]
bads3 = ootdata[ootdata['org'] == 1]
numgoods3 = len(goods3)
numbads3 = len(bads3)


topRows3 = int(round(len(ootdata)*0.03))

temp3 = ootdata.head(topRows3)

needed3 = temp3.loc[:,'org']

FDR3 = sum(needed3)/numbads3


In [24]:
### 10-8-1 result
print(FDR1, FDR2, FDR3)

0.7192982456140351 0.5731225296442688 0.37988826815642457


In [43]:
### 5-5-1 result
print(FDR1, FDR2, FDR3)

0.6985645933014354 0.5810276679841897 0.39664804469273746


In [66]:
### 5-6-1 result
print(FDR1, FDR2, FDR3)

0.7017543859649122 0.6047430830039525 0.3743016759776536


In [85]:
### 6-6-1 result
print(FDR1, FDR2, FDR3)

0.7001594896331739 0.5731225296442688 0.3575418994413408


In [104]:
### 5-4-1 result
print(FDR1, FDR2, FDR3)

0.7017543859649122 0.616600790513834 0.3743016759776536


In [12]:
# round predictions
rounded = [round(x[0]) for x in y_pred]
print(rounded)

[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,

In [13]:
y_train

Fraud
0          0
1          0
2          0
3          0
4          0
5          0
6          0
7          0
8          0
9          0
10         0
11         0
12         0
13         0
14         0
15         0
16         0
17         0
18         0
19         0
20         0
21         0
22         0
23         0
24         0
25         0
26         0
27         0
28         0
29         0
...      ...
58749      0
58750      0
58751      0
58752      0
58753      0
58754      0
58755      0
58756      0
58757      0
58758      0
58759      0
58760      0
58761      0
58762      0
58763      0
58764      0
58765      0
58766      0
58767      0
58768      0
58769      0
58770      0
58771      0
58772      0
58773      0
58774      0
58775      0
58776      0
58777      0
58778      0

[58779 rows x 1 columns]

In [14]:
y_train['Fraud'].value_counts()

0    58152
1      627
Name: Fraud, dtype: int64

In [19]:
rounded.count(1)

303