In [28]:
import numpy as np
import pandas as pd

In [29]:
X_train = pd.read_csv('X_train_scaled.csv')
X_test = pd.read_csv('X_test_scaled.csv')
y_train = pd.read_csv('y_train.csv')
y_test = pd.read_csv('y_test.csv')
X_oot = pd.read_csv('X_oot_scaled.csv')
y_oot = pd.read_csv('y_oot.csv')

In [30]:
X_train

amt_max_cardstate_15d  amt_max_cardstate_31d  freq_card_2d  \
0                  -0.507977              -0.551390     -0.297022   
1                  -0.500745              -0.544749     -0.297022   
2                   0.341408               0.228539     -0.297022   
3                  -0.512046              -0.554880      0.425416   
4                  -0.496668              -0.541005      0.305009   
5                  -0.156513              -0.228666     -0.297022   
6                  -0.505305              -0.548936     -0.297022   
7                  -0.511882              -0.554975      0.666229   
8                  -0.320987              -0.379690     -0.056210   
9                  -0.012961              -0.096852     -0.297022   
10                  0.041105              -0.047207     -0.176616   
11                 -0.204666              -0.272881     -0.297022   
12                 -0.421413              -0.019503     -0.297022   
13                 -0.501995              -0.545897     -0.297022   
14                  0.291782               1.365679     -0.176616   
15                 -0.439602              -0.488605     -0.056210   
16                  1.134453               0.985466     -0.056210   
17                 -0.346805              -0.403397     -0.297022   
18                 -0.364132              -0.419307     -0.056210   
19                  1.326727               1.133285     -0.297022   
20                  0.257870               0.151832     -0.176616   
21                 -0.020391              -0.103675     -0.297022   
22                 -0.444386              -0.443765     -0.297022   
23                 -0.390854              -0.443844      0.184603   
24                 -0.276076              -0.338452     -0.056210   
25                  0.374277               0.258720     -0.297022   
26                 -0.419249              -0.469917     -0.297022   
27                 -0.512046              -0.555126      0.425416   
28                 -0.505934              -0.549514      1.268260   
29                 -0.287817              -0.349232     -0.297022   
...                      ...                    ...           ...   
58749              -0.516046              -0.539540     -0.176616   
58750              -0.233061              -0.298954     -0.297022   
58751               0.084207              -0.007630     -0.297022   
58752               1.381534               1.183611      0.666229   
58753              -0.447524              -0.495880     -0.297022   
58754              -0.510331              -0.549039      0.064197   
58755              -0.473247              -0.519499     -0.297022   
58756              -0.511882              -0.554975     -0.176616   
58757              -0.298997               0.229829     -0.297022   
58758               0.676373               0.536113      0.305009   
58759              -0.099973               0.476986      0.305009   
58760               0.838736               0.685198     -0.297022   
58761              -0.053717              -0.056365     -0.297022   
58762               0.903129               0.744326      0.064197   
58763              -0.088207              -0.165945     -0.297022   
58764              -0.081474              -0.159763     -0.176616   
58765              -0.477833              -0.451166     -0.297022   
58766              -0.422689              -0.473075     -0.297022   
58767              -0.468350              -0.515003     -0.297022   
58768               0.041105              -0.047207     -0.176616   
58769              -0.504831               0.072029      0.545822   
58770               0.213510               0.111100     -0.297022   
58771              -0.484737              -0.530050     -0.297022   
58772              -0.347883              -0.404386      0.184603   
58773              -0.518580              -0.561126     -0.297022   
58774              -0.489470              -0.534396      0.064197   
58775

In [31]:
y_test['Fraud'].value_counts()

0    24938
1      253
Name: Fraud, dtype: int64

In [32]:
%%time
from sklearn.svm import SVC

svc=SVC(probability = True)
svc.fit(X_train, y_train)

/Users/shihuizhang/anaconda3/lib/python3.7/site-packages/sklearn/utils/validation.py:761: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


CPU times: user 48.5 s, sys: 924 ms, total: 49.5 s
Wall time: 49.4 s


In [33]:
y_train_pred=svc.predict(X_train)
y_test_pred=svc.predict(X_test)
y_oot_pred=svc.predict(X_oot)

In [7]:
###y_pred

array([0, 0, 0, ..., 0, 0, 0])

In [34]:
a_train=[]
prob_train = svc.predict_proba(X_train)
for probabilty in prob_train:
    a_train.append(probabilty[1])
a_train

[0.007432342785836181,
 0.0070136949613633275,
 0.007669104040234063,
 0.003841893507735411,
 0.004907557388334685,
 0.007855388487819241,
 0.006937268491824707,
 0.0005086462205103995,
 0.00685600888466558,
 0.007962224389952633,
 0.007202552298635069,
 0.007994470195846969,
 0.008009875066419354,
 0.00797912698423114,
 0.002241122886819314,
 0.0076925906007014365,
 0.004608187650531257,
 0.007489618623368497,
 0.006857639522552091,
 0.00520462510889961,
 0.007615795093379865,
 0.008003188934993017,
 0.007319354586189974,
 0.006206430977486471,
 0.006758111176877133,
 0.007239795471996516,
 0.007258948449745874,
 0.0011816630496712835,
 0.0002553313774842986,
 0.007548022700889533,
 0.00732285723116208,
 0.006148752299202929,
 0.007384303005107341,
 0.001413498635388672,
 0.006965502453982745,
 0.0072840140540645516,
 0.004694622877332204,
 0.006173210550013529,
 0.9999999976563451,
 0.007038905669671895,
 0.008004489208978035,
 0.007007883567290776,
 0.006605862746711285,
 0.00777912

In [35]:
a_test=[]
prob_test = svc.predict_proba(X_test)
for probabilty in prob_test:
    a_test.append(probabilty[1])
a_test

[0.007173802402908792,
 0.004568666664893869,
 0.008022622149372587,
 0.006178236988317154,
 0.007809371189555928,
 0.007364422030828246,
 0.007376535222936708,
 0.007834201427881366,
 0.007055626948127351,
 0.0004726232604371266,
 0.006954039307440441,
 0.005473974450623474,
 0.007990948504431309,
 0.006918422647878481,
 0.006556260906302378,
 0.006911488123941161,
 0.007878127024847503,
 0.006969447507680372,
 0.004479532578745937,
 0.007843609124128886,
 0.9589805259576802,
 0.0030579699326559913,
 0.007906027157469315,
 0.006926763789903488,
 0.005612972719792356,
 0.00806487708475467,
 0.008147915356581712,
 0.007511540992163311,
 0.006992650463037003,
 0.008130580214109825,
 0.007306283651477277,
 0.006410039963251969,
 0.007120584239506515,
 0.0060669801796548834,
 0.006238476145293417,
 0.007685977978855697,
 0.005064696358577238,
 0.005707464242690086,
 0.006453934012772295,
 0.00563792704910626,
 0.007230681428696399,
 0.007255738522978752,
 0.005212505921720308,
 0.007052373

In [36]:
a_oot=[]
prob_oot = svc.predict_proba(X_oot)
for probabilty in prob_oot:
    a_oot.append(probabilty[1])
a_oot

[0.05474539823065798,
 0.0024181435164644543,
 0.008160161658902296,
 0.008016795637403417,
 0.005142490064467456,
 0.007738957010416751,
 0.00679974841562278,
 0.006726108852838278,
 0.0065631959430992905,
 0.00833989775566861,
 0.008494740968441078,
 0.007110824720791847,
 0.008125995941572605,
 0.007198045861826693,
 0.006788931287953759,
 0.007966634035478802,
 0.008423113630397456,
 0.00808268595034112,
 0.0074630073254714204,
 0.00833547505470916,
 0.007943059122509066,
 0.008219052117910944,
 0.007848249872384099,
 0.006688334805843245,
 0.006878050821398344,
 0.0071865062708304055,
 0.007122957173913586,
 0.006068203776474234,
 0.00859458835248653,
 0.007450680897711934,
 0.005457780277209828,
 0.002621249316454576,
 0.005434053369784513,
 0.004615691969986568,
 0.004803228687035633,
 0.00802713520138187,
 0.00791811342429309,
 0.007318079085903927,
 0.008280812674721092,
 0.008744733147672507,
 0.00691748599703552,
 0.0075996206992924534,
 0.006555986742608868,
 0.006833798209

In [37]:
newDF_train = X_train
newDF_train['prob'] = a_train
newDF_train['org'] = y_train
newDF_train.sort_values(by=['prob'],ascending = False, inplace = True)

newDF_test = X_test
newDF_test['prob'] = a_test
newDF_test['org'] = y_test
newDF_test.sort_values(by=['prob'],ascending = False, inplace = True)

newDF_oot = X_oot
newDF_oot['prob'] = a_oot
newDF_oot['org'] = y_oot
newDF_oot.sort_values(by=['prob'],ascending = False, inplace = True)

In [38]:
from sklearn.metrics import confusion_matrix
confusion_matrix = confusion_matrix(y_train, y_train_pred)
print(confusion_matrix)

[[58137    15]
 [  411   216]]


In [39]:
from sklearn.metrics import confusion_matrix
confusion_matrix = confusion_matrix(y_test, y_test_pred)
print(confusion_matrix)

[[24936     2]
 [  189    64]]


In [40]:
from sklearn.metrics import confusion_matrix
confusion_matrix = confusion_matrix(y_oot, y_oot_pred)
print(confusion_matrix)

[[12239     9]
 [  154    25]]


In [41]:
#FDR 3% train
traindata = newDF_train
goods1 = traindata[traindata['org']==0]
bads1 = traindata[traindata['org'] == 1]
numgoods1 = len(goods1)
numbads1 = len(bads1)


topRows1 = int(round(len(traindata)*0.03))

temp1 = traindata.head(topRows1)

needed1 = temp1.loc[:,'org']

FDR1 = sum(needed1)/numbads1


In [42]:
#FDR 3% test
testdata = newDF_test
goods2 = testdata[testdata['org']==0]
bads2 = testdata[testdata['org'] == 1]
numgoods2 = len(goods2)
numbads2 = len(bads2)


topRows2 = int(round(len(testdata)*0.03))

temp2 = testdata.head(topRows2)

needed2 = temp2.loc[:,'org']

FDR2 = sum(needed2)/numbads2

In [43]:
#FDR 3% oot
ootdata = newDF_oot
goods3 = ootdata[ootdata['org']==0]
bads3 = ootdata[ootdata['org'] == 1]
numgoods3 = len(goods3)
numbads3 = len(bads3)


topRows3 = int(round(len(ootdata)*0.03))

temp3 = ootdata.head(topRows3)

needed3 = temp3.loc[:,'org']

FDR3 = sum(needed3)/numbads3

In [44]:
print(FDR1, FDR2, FDR3)

0.6156299840510366 0.5296442687747036 0.37988826815642457
